name: ATCS_GPU
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiosignal=1.3.1
  - appdirs=1.4.4
  - arrow-cpp=11.0.0
  - async-timeout=4.0.2
  - attrs=22.2.0
  - aws-c-auth=0.6.26
  - aws-c-cal=0.5.21
  - aws-c-common=0.8.14
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.20
  - aws-c-http=0.7.6
  - aws-c-io=0.13.19
  - aws-c-mqtt=0.8.6
  - aws-c-s3=0.2.7
  - aws-c-sdkutils=0.1.8
  - aws-checksums=0.1.14
  - aws-crt-cpp=0.19.8
  - aws-sdk-cpp=1.10.57
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - dataclasses=0.8
  - datasets=2.11.0
  - dill=0.3.6
  - ffmpeg=4.3
  - filelock=3.11.0
  - freetype=2.12.1
  - fsspec=2023.4.0
  - gflags=2.2.2
  - glog=0.6.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - huggingface_hub=0.13.4
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.3.0
  - importlib_metadata=6.3.0
  - intel-openmp=2021.4.0
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.0
  - libarrow=11.0.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcrc32c=1.1.2
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.0.25
  - libcurand=10.3.2.56
  - libcurl=8.0.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgoogle-cloud=2.8.0
  - libgrpc=1.52.1
  - libhwloc=2.9.0
  - libiconv=1.17
  - libnghttp2=1.52.0
  - libnpp=11.7.4.75
  - libnsl=2.0.0
  - libnuma=2.0.16
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libthrift=0.18.1
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.4
  - libzlib=1.2.13
  - llvm-openmp=16.0.1
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.6
  - nltk=3.7
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.0
  - orc=1.8.3
  - packaging=23.1
  - parquet-cpp=1.5.1
  - pip=22.2.2
  - pooch=1.4.0
  - pthread-stubs=0.4
  - pycparser=2.21
  - pyopenssl=23.1.1
  - pysocks=1.7.1
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python-xxhash=3.2.0
  - python_abi=3.10
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2023.3
  - re2=2023.02.02
  - readline=8.2
  - requests=2.28.2
  - s2n=1.3.41
  - setuptools=67.6.1
  - six=1.16.0
  - snappy=1.1.10
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tqdm=4.65.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - ucx=1.14.0
  - urllib3=1.26.15
  - wheel=0.40.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - aiofiles==22.1.0
    - aiohttp==3.8.4
    - aiosqlite==0.18.0
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - babel==2.12.1
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - brotlipy==0.7.0
    - cachetools==5.3.0
    - certifi==2022.12.7
    - cffi==1.15.1
    - click==8.0.4
    - comm==0.1.3
    - contourpy==1.0.7
    - cryptography==40.0.1
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - executing==1.2.0
    - fastjsonschema==2.16.3
    - fonttools==4.39.3
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - google-auth==2.17.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.53.0
    - ipykernel==6.22.0
    - ipython==8.12.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.1.1
    - json5==0.9.11
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter-client==8.1.0
    - jupyter-core==5.3.0
    - jupyter-events==0.6.3
    - jupyter-server==2.5.0
    - jupyter-server-fileid==0.9.0
    - jupyter-server-terminals==0.4.4
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.4
    - jupyterlab==3.6.3
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.22.0
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - markdown==3.4.3
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.5
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - nbclassic==0.5.5
    - nbclient==0.7.3
    - nbconvert==7.3.1
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - notebook==6.5.4
    - notebook-shim==0.2.2
    - numpy==1.23.5
    - oauthlib==3.2.2
    - pandas==2.0.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.5.0
    - platformdirs==3.2.0
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.38
    - protobuf==3.19.6
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==11.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pygments==2.15.0
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-json-logger==2.0.7
    - pytorch-lightning==1.7.7
    - pyyaml==6.0
    - pyzmq==25.0.2
    - regex==2022.7.9
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - seaborn==0.12.2
    - send2trash==1.8.0
    - sniffio==1.3.0
    - soupsieve==2.4
    - stack-data==0.6.2
    - tabulate==0.9.0
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torch==1.13.0
    - torchaudio==0.13.0
    - torchmetrics==0.11.4
    - torchvision==0.14.0
    - tornado==6.2
    - traitlets==5.9.0
    - uri-template==1.2.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - werkzeug==2.2.3
    - widgetsnbextension==4.0.7
    - xxhash==0.0.0
    - y-py==0.5.9
    - yarl==1.8.2
    - ypy-websocket==0.8.2
