#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=18:00:00
#SBATCH --mem=32000M
#SBATCH --output=train_bilstm_max_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/SentenceRepresentations_NLI
source activate dl2022
# Run your code
srun python train_nli.py --encoder "bilstm" --num_epochs 20 --encoder_pooling "max"